### ISSUE TITLE
What is the right way to Register/Login to BeagleBoard.org?

### ISSUE THREAD

**Issue by mingca** [beagleboard/beagleboard-org#1]
Even Wordpress.com doesn't support OpenID naturally although community supports several openid provider plugins but we can install them only when the user is on Enterprise(paid plan), not available on free plan.
I'd love to singup to BeagleBoard and want to get help. 
Thanks for any comments in advance.

**Comment by jadonk** [comment]
Use hackster.io/beagleboard for now as the wordpress openid support is flaky.
